### ISSUE TITLE
Use gitignore and npmignore at the same time

### ISSUE THREAD

**Issue by yordis** [npm/npm-packlist#13]
Right now most of my packages requires me to add `.npmignore` because I can't add everything to te `gitignore`.

But because of this I notice that this package either uses `npmignore` or `gitignore` so I see myself in a position of duplicating most of the content of my `gitignore` into my `npmignore` but except the files that I actually want to keep.

**Comment by isaacs** [comment]
Yes, that is what you have to do.

Perhaps you could put the files you want to include in the `files` array in `package.json`?

**Comment by yordis** [comment]
@isaacs yeah, definitely started using `files` instead
