### ISSUE TITLE
[BUG] npx npm-packlist broken

### ISSUE THREAD

**Issue by GeoffreyEmerson** [npm/npm-packlist#164]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

Official npm docs ([here](https://docs.npmjs.com/cli/v8/commands/npm-publish)) recommend using `npx npm-packlist`.

> To see what will be included in your package, run `npx npm-packlist`.

I believe that feature was broken in https://github.com/npm/npm-packlist/pull/128 with the removal of the "bin" property from "package.json".

Current behavior is:

```
$ npx npm-packlist
npm ERR! could not determine executable to run

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/username/.npm/_logs/2023-03-19T00_30_14_201Z-debug-0.log
```

@nlf noted in the PR that "the npm-packlist bin has also been removed." but did not explain why.

### Expected Behavior

`npx npm-packlist` should a list of files that will be included during `npm publish`.

### Steps To Reproduce

1. In a repo of a project that is ready to be published to npm
2. Execute on the command line `npx npm-packlist`

### Environment

- npm: 8.19.3
- Node: 18.13.0
- OS: macOS 13.2.1
- platform: Macbook Pro
- iTerm2
- zsh

**Comment by staff0rd** [comment]
A workaround for now is `npx npm-packlist@6`

**Comment by staff0rd** [comment]
Correct/new way is to run `npm pack --dry-run` . [Docs are being updated](https://github.com/npm/cli/pull/6306)

**Comment by wraithgar** [comment]
Unfortunately due to the way our dependencies are set up this bin can't work, there was a circular dependency on `@npmcli/arborist` that would prevent us from updating our packages.

Realistically this is a bad idea anyways since this package doesn't parse your config or cli args like npm itself, so npm will always be the more correct way to do this.
