### ISSUE TITLE
[BUG] Behavior change for glob like foo/**/* in 8.0.1 relative to 8.0.0.

### ISSUE THREAD

**Issue by danpere** [npm/npm-packlist#212]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

`foo/**/*` matches nothing.

### Expected Behavior

`foo/**/*` recursively matches all files and directories under the directory `foo/`.

### Steps To Reproduce

I modified the test `test/package-json-directory-glob.js` (danpere/npm-packlist@43c6d5dc3f7b6ebc4c7d664a230506658600605b) to display the behavior:

1. Checkout the branch [bug/star-star-slash-star from my fork danpere/npm-packlist](https://github.com/danpere/npm-packlist/tree/bug/star-star-slash-star).
2. Run `npm test`.
3. Observe that the test fails.
4. Checkout the branch [bug/star-star-slash-star-revert-205 from my fork danpere/npm-packlist](https://github.com/danpere/npm-packlist/tree/bug/star-star-slash-star-revert-205), which differs only in that I ran `git revert cd5ddbd9fc7069d62fd89e0de741523e408c889b` to revert #205.
5. Run `npm test`.
6. Observe that the test passes.

### Environment

- npm: 10.2.5
- Node: 20.10.0
- OS: Windows 11 Enterprise Version 10.0.22631 Build 22631
- platform: Surface Book 2

**Comment by wraithgar** [comment]
This is a regression of https://github.com/npm/npm-packlist/pull/147.

npm currently supports an invalid interpretation of a glob pattern, treating a trailing `/*` as if it were a `/**`.  This needs to be fixed but users would also best serve themselves by fixing their glob patterns.

**Comment by ljharb** [comment]
I’m confused; double star should match every level of directories, meaning that the final * only needs to apply to top-level files. What’s incorrect about this glob?

**Comment by wraithgar** [comment]
I may be mistaken.  The bug needs fixing either way.

**Comment by danpere** [comment]
Our workaround was to change the glob in our `package.json` to `foo/*` (`foo` also would have worked). We had `foo/**/*` because that's the recursive glob for matching all files under a directory and whoever wrote that didn't realize that including a directory in `package.json` already includes all of its subdirectories recursively, so the globbing is actually unnecessary.
