### ISSUE TITLE
"core" folder missing on NPM registry

### ISSUE THREAD

**Issue by TheOptimisticFactory** [npm/npm-packlist#24]
Greetings, 

The [Pull-Request n°8](https://github.com/npm/npm-packlist/pull/8) got one of our Lerna projects broken due to a folder named "/lib/core" being missing on the NPM registry.

After some debugging, I have tracked the origin of the missing folder to the aforementioned PR.
The missing folder has nothing to do with a Linux core dump but instead contains the core components of the private tool we are hosting on NPM.

For the time being, we worked around the issue by adding `!/lib/core` in the local folder of the tool so that it overrides the default blacklist.

An option to disable that behavior would be nice as mentioned in the PR itself: https://github.com/npm/npm-packlist/pull/8#discussion_r171022093

**Comment by RomainMuller** [comment]
Also affected as this was factored in `npm@6.8.0`. This was an extremely surprising change and I would expect it to breaks tuff somewhat pervasively.

**Comment by JohnRGee** [comment]
A couple of observations:
1) the [README](https://github.com/npm/npm-packlist) here and the corresponding info in [npm-developers](https://docs.npmjs.com/misc/developers#keeping-files-out-of-your-package) have not been updated to mention core.

2) I expect the intent of the change is to exclude files named core but it also matches folders named core. I wonder whether can achieve that with something like "core", "!core/"

**Comment by JohnRGee** [comment]
The `core` change can also affect installs such as from github, and not just `npm pack` and `npm publish`: https://npm.community/t/npm-pack-leaving-out-files-6-8-0-only/5382/7

**Comment by AitorGuerrero** [comment]
I have a "common" utils repo required through git in almost all my microservices, (basically, types and some classes to ease the communication between them). Suddenly, all my classes and types from the "core" service disappeared in my services.

I think this behaviour should be undone as it breaks functional code, and is included in a minor update.

**Comment by isaacs** [comment]
I agree this is probably not worthwhile to include `core` in the list of default exclusions.

I'm talking to the team and suggesting that we back that name out of the list in the next release.

In the meantime, anyone affected by this can either add `core` to the package.json files list, or create a `.npmignore` file containing `!core`, as a workaround.

**Comment by LvChengbin** [comment]
It's really a surprise.
