### ISSUE TITLE
npm packlist version change from 6.0.0 to 8.0.0

### ISSUE THREAD

**Issue by ramdaggumati** [npm/npm-packlist#243]
### Is there an existing issue for this?

- [ ] I have searched the existing issues

### Current Behavior

updating the package from 6.0.0 to 8.0.0 and performing the npm run packlist throwing error as:
npm ERR! could not determine executable to run

### Expected Behavior

should list the file of the directory

### Environment

- npm:8.19.3
- Node:18.13.0
- platform: Macbook Pro

**Comment by wraithgar** [comment]
Not enough info here to reproduce.
