### ISSUE TITLE
Non-root non-bundledDep package.json files

### ISSUE THREAD

**Issue by larsgw** [npm/npm-packlist#28]
In [npm.community#6140](https://npm.community/t/npm-pack-publish-does-not-pack-files-ignored-by-inner-package-json/6140) someone wants to have a `package.json` in a `template/` folder, pretty reasonable stuff. However, the `package.json` has a `files` field which, in their use case, should be ignored when packing/publishing the parent package. There is a specific test case for the current behavior, but I was wondering if `onPackageJson` was originally intended for all nested `package.json`s, or just those in `bundleDependencies`.

**Comment by isaacs** [comment]
Addressed by #40.
