### ISSUE TITLE
.DS_Store is included in tarball

### ISSUE THREAD

**Issue by feross** [npm/npm-packlist#37]
`npm@6.9.0` is including `.DS_Store` files in packages at publish time. Here's a reproducible test case:

```
git clone https://github.com/feross/unmute-ios-audio
cd unmute-ios-audio
touch .DS_Store
npm pack
```

You'll see that `.DS_Store` is included in the pack when it should not be.

**Comment by DanielRuf** [comment]
Probably already fixed by https://github.com/npm/npm-packlist/commit/7fcd045b7a46ef06651763e41d6c65393d509ef5.

**Comment by isaacs** [comment]
Indeed, should be fixed in the latest release.  Thanks!
