### ISSUE TITLE
Not only root-level node_modules ignored

### ISSUE THREAD

**Issue by rodrigodc** [npm/npm-packlist#4]
Hello,

As described in this npm [issue](https://github.com/npm/npm/issues/18508), not only the root-level `./node_modules` directory is being ignored, but _any_ other directories called `node_modules`, for example `./lib/node_modules` or `./src/node_modules` or `./a/b/c/node_modules`.

The [readme](https://github.com/npm/npm-packlist/blob/master/README.md) file here mentions `Everything in the root node_modules is ignored`, and says nothing about other `node_modules` directories, so I assume the intention might have been to ignore only the root-level one.

So, what is the expected behavior? To ignore only the root-level `node_modules`, or any?

Thank you.

**Comment by isaacs** [comment]
Fixed on the latest release, in https://github.com/npm/npm-packlist/commit/9b72c4f42cf161e17a780dff6784305522564d12.  Will be included in next npm release.

Thanks!
