### ISSUE TITLE
[QUESTION] Breaking changes in v2?

### ISSUE THREAD

**Issue by robertknight** [npm/npm-packlist#43]
The major version of this package was bumped recently but I couldn't find any release notes indicating what the potentially breaking changes were.

From skimming recent issues it looks like https://github.com/npm/npm-packlist/issues/39 was the only reason for this?

Is there anything that consumers of the package should watch out for?

**Comment by isaacs** [comment]
The breaking change is detailed here: https://github.com/npm/npm-packlist#interaction-between-packagejson-and-npmignore-rules

It's extremely subtle, and it's unlikely that anyone was depending on the old behavior.  (In fact, it's been a regular source of complaints.)  But subtle changes in package file inclusion are worthy of a semver-major bump.
