### ISSUE TITLE
[BUG] npm-normalize-package-bin is not in package.json

### ISSUE THREAD

**Issue by fearthecowboy** [npm/npm-packlist#45]
# What / Why
You added a `require('npm-normalize-package-bin') `

https://github.com/npm/npm-packlist/blob/master/index.js#L20

the package `npm-normalize-package-bin` is not in the package.json, consumers will not have it.

**Comment by evocateur** [comment]
https://github.com/npm/npm-packlist/commit/196df5ceaa55f63a9a36aaafb98e9e37cce4e423 seems to cover all the bases, where are you seeing this "missing" dependency?

**Comment by christopherthielen** [comment]
It's missing in the 1.4.7 release.  
See this commit: https://github.com/npm/npm-packlist/commit/ec4d56e7b02e596c5f5a21acdb2b524f51aaa3a0

**Comment by isaacs** [comment]
Fixed by #49
