### ISSUE TITLE
[BUG] Can't get it to ignore README.md

### ISSUE THREAD

**Issue by otherguy** [npm/npm-packlist#59]
# What / Why
I cannot get this to ignore `README.md`. Am I doing something wrong?

I'm using this with `npm-pack-zip` (1.2.9), which installs `1.4.8` of `npm-packlist`.

My `package.json` has no `files` section, but I added a `.npmignore` file:

```
.git
.editorconfig
README.md
.circleci
.github
dist
node_modules
.tool-versions
```

Adding `*.md` also does nothing. There is a `.gitignore` but it does not mention (include) `README.md` or any other `.md` file.

## Where
- Npm 7.6.3
- Node 15.12.0
- npm-packlist 1.4.8

### Current Behavior
`README.md` is not excluded

### Expected Behavior
`README.md` should be excluded

**Comment by nlf** [comment]
this is intentional and deliberate, though it definitely could be documented more appropriately. any files named readme, copying, license, licence, notice, changes, changelog, or history with any casing (upper/lower is ignored) and any file extension will always be packed.
