### ISSUE TITLE
`/lib/node_modules` not included

### ISSUE THREAD

**Issue by piranna** [npm/npm-packlist#6]
According to https://github.com/npm/npm-packlist/blob/991cd69bd1fd8fc88dd47238587d2daf6e0057ad/index.js#L94 and https://github.com/npm/npm-packlist/blob/master/test/empty-npmignore.js#L46-L50, `/lib/node_modules` folders should be included when doing `npm pack`, but for https://github.com/unifyme/twilio.js the folder https://github.com/UnifyMe/twilio.js/tree/master/lib/node_modules/AudioPlayer. I've only managed to do so by moving it to `/node_modules` and setting it as a `bundledDependency` (I could do it that way, but then it would complicate the `.gitignore` file...), otherwise it's not included at all. Not sure if my module has a corner case or I'm doing something wrong with it...

**Comment by piranna** [comment]
If it's of info, I'm using npm `v5.5.1`.

**Comment by piranna** [comment]
Ok... npm `5.5.1`, although is the last one, [it uses npm-packlist `1.1.9`](https://github.com/npm/npm/blob/fb28e5868a9dbbe21a15f23fe8cf8b3703e8adf2/package.json#L86). Suppose it will be fixed in the next version of npm.

**Comment by isaacs** [comment]
@piranna I'm closing, because it looks like this is no longer an issue.  Please reopen if you're still running into this problem.

**Comment by piranna** [comment]
It's ok for me :-)
