### ISSUE TITLE
[BUG] Missing CHANGELOG

### ISSUE THREAD

**Issue by hyrious** [npm/npm-packlist#62]
# What / Why

I've written a small library with `CHANGELOG.md` in its root folder. NPM pack it into the result, you can check that [here](https://cdn.jsdelivr.net/npm/@hyrious/esbuild-plugin-style/). But `npx npm-packlist` does not report it:

```bash
> npx npm-packlist
index.js
package.json
index.js.map
README.md
index.ts
LICENSE.txt
```

**Comment by aarongoldenthal** [comment]
Several other files that are always included per https://docs.npmjs.com/cli/v7/configuring-npm/package-json#files are also missing (for example HISTORY, NOTICE).

**Comment by AkiJoey** [comment]
Do not including `CHANGES/CHANGELOG/HISTORY/NOTICE` is an intended change introduced by #61.
