### ISSUE TITLE
[BUG] Docs still say CHANGELOG will be included in the packlist by default

### ISSUE THREAD

**Issue by leilapearson** [npm/npm-packlist#66]
# What / Why

Was trying to figure out why `pack` and `publish` were no longer including my `CHANGELOG.md` file by default after I upgraded to the latest npm.  Looked around for documentation and eventually discovered this was an intentional change (wouldn't mind a bit of background on that) but some of the current documentation still says it should be included by default.

### Steps to Reproduce
* Search for CHANGELOG in npm-packlist README.md
* Search for CHANGELOG in https://docs.npmjs.com/cli/v8/using-npm/developers

### Expected Behavior
* Docs should match actual behavior with respect to CHANGELOG and other files that are no longer included by default.

## References
  * Related to npm/cli#3334

**Comment by shaneog** [comment]
> (wouldn't mind a bit of background on that)

+1 to this.

This just caught me by surprise also.
