### ISSUE TITLE
npm happily creates packages that won't unpack on windows

### ISSUE THREAD

**Issue by chriseppstein** [npm/npm-packlist#9]
I got this bug recently: https://github.com/mahirshah/css-property-parser/issues/21 because a filename had an asterisk in it. Evidently windows gets mad about that. I worked around the issue by renaming the files, but it seemed like the sort of thing that npm might want to raise an error about or handle somehow so that it's not an error.

**Comment by isaacs** [comment]
Note: There may be a way to escape these characters in node tar, like we do for `:` and `<`.

**Comment by isaacs** [comment]
There does not appear to be a way to make this work at the tar level.

I think the answer here is just to disallow them in npm-packlist (like how we disallow symlinks), since it's really about application portability.
